baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "ja-jp"
defaultContentLanguage = 'ja'
title = "Tomoto Lab"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]

  [params.logo]
    mobile = "images/logo/banner.svg"
    mobile_height = "36px"
    desktop = "images/logo/banner.svg"
    desktop_height = "36px"
    alt = "Tomoto Lab"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@200;400;800&display=swap'
    heading = "M Plus 1p"
    base = "M Plus 1p"
    lighter_weight = "200"
    bolder_weight = "800"


  [params.colors]
    primary = "#008037"
    black = "#49757a"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#015c40"

  [params.footer]
    copyright_text = '© Takahito Tomoto Laboratory.'

  [params.team]
    alt_image = 'images/logo/logo-circle.svg'

[menu]
  # Main Menu
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "東本崇仁"
    url = "/tomoto/"
    weight = 2

  [[menu.main]]
    name = "研究内容"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "構成員"
    url = "/members/"
    weight = 4

  [[menu.main]]
    name = "研究業績"
    url = "/publications/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "東本崇仁"
    url = "/tomoto/"
    weight = 2

  [[menu.footer]]
    name = "研究内容"
    url = "/research/"
    weight = 3

  [[menu.footer]]
    name = "構成員"
    url = "/members/"
    weight = 4

  [[menu.footer]]
    name = "研究業績"
    url = "/publications/"
    weight = 5
